services:
  # Backend service
  - type: web
    name: virallens-backend
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGO_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://virallens-frontend.onrender.com

  # Frontend service
  - type: web
    name: virallens-frontend
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: VITE_API_URL
        value: https://virallens-backend.onrender.com
    buildCommand: echo "Building frontend..."

databases:
  - name: mongodb-atlas
    plan: starter
    region: oregon
